### ISSUE TITLE
I cant make the file

### ISSUE THREAD

**Issue by ICantCodecauseimanoob** [2much4u/PS4-GTA-V-Native-Caller#1]
When I put make in terminal for PS4-GTA-V-Menu-Base-master I get this fatal error in terminal saying "include/type.h:3:19: fatal error: types.h: No such file or directory compilation terminated.
Makefile:30 recipe for target 'build/kern.o' failed
make: ***[build/kern.o] Error 1"
Any ideas on how to fix this or any help?

**Comment by Flatracer** [comment]
You need the sdk linked in the description
